export default {
    getHomeData2:()=>{
       return{
           code:200,
           data:{
               countData:[
                   {
                       name:"今日支付订单",
                       value:1234,
                       icon:"SuccessFilled",
                       color:"#2ec7c9"
                   },
                   {
                       name:"今日收藏订单",
                       value:190,
                       icon:"StarFilled",
                       color:"#ffb980"
                   },
                   {
                       name:"今日未支付订单",
                       value:1230,
                       icon:"GoodsFilled",
                       color:"#5ablef"
                   },
                   {
                       name:"本月支付订单",
                       value:6657,
                       icon:"SuccessFilled",
                       color:"#2ec7c9"
                   },
                   {
                       name:"本月收藏订单",
                       value:6657,
                       icon:"SStarFilled",
                       color:"#ffb980"
                   },
                   {
                       name:"本月未支付订单",
                       value:6657,
                       icon:"GoodsFilled",
                       color:"#5ablef"
                   },
               ]
           }
       }
    }
}